# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
#  database: tv_development
  database: mythconverg
  pool: 5
#  username: root
  username: mythtv
  password:
# password needed to be quoted. (space after ':')
#
#  socket: /var/run/mysqld/mysqld.sock
  port: 3306
  host: mjc3
# OR host: 192.168.1.93  ???
# BUT NOT host: localhost  (Information possibly old)

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: tv_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
#  database: tv_production
  database: mythconverg
#  username: root
  username: mythtv
  password: 
# password needed to be quoted. (space after ':')
#
#  socket: /var/run/mysqld/mysqld.sock  #: Either socket or port+host works
  port: 3306
  host: 127.0.0.1
# OR host: 192.168.1.93  ???
# BUT NOT host: localhost
