# -*- coding: undecided -*-


# Add your own tasks in files placed in lib/tasks ending in .rake,
#
# For example lib/tasks/capistrano.rake, and they will automatically be 
# available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'

# require 'rake/rdoctask'
# -->
require 'rdoc/task'
# RDoc::Task.new do |rdoc|

# You may need to add gem 'rdoc' to your Gemfile, too. While you’re at it,
# you might want to add rdoc/ to your .gitignore, too


require 'tasks/rails'
