<%
  @path = "#{Rubber.root}/config/mongrel_cluster.yml"
%>
---
user: <%= rubber_env.app_user %>
group: <%= rubber_env.app_user %>
cwd: <%= Rubber.root %>
port: "<%= rubber_env.mongrel_base_port %>"
environment: <%= Rubber.env %>
address: <%= rubber_env.host %>
pid_file: tmp/pids/mongrel.pid
servers: <%= rubber_env.mongrel_count %>
