---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod1
  domain: emeyekayee.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-24e8c77d
  image_type: m1.small
  image_id: ami-0d153248
  security_groups:
  - tvg_production_default
  - tvg_production_web
  - tvg_production_prod1
  - tvg_production_haproxy
  - tvg_production_app
  - tvg_production_passenger
  - tvg_production_apache
  - tvg_production_db
  - tvg_production_mysql
  - tvg_production_mysql_master
  - tvg_production_collectd
  - tvg_production_monit
  external_host: ec2-50-18-240-209.us-west-1.compute.amazonaws.com
  external_ip: 50.18.240.209
  internal_host: ip-10-171-153-15.us-west-1.compute.internal
  internal_ip: 10.171.153.15
  zone: us-west-1c
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
