---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: emeyekayee.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-3e153467
  image_type: t1.micro
  image_id: ami-0d153248
  security_groups:
  - tvg_production_default
  - tvg_production_web
  - tvg_production_production
  - tvg_production_haproxy
  - tvg_production_app
  - tvg_production_passenger
  - tvg_production_apache
  - tvg_production_db
  - tvg_production_mysql
  - tvg_production_mysql_master
  - tvg_production_collectd
  - tvg_production_monit
  external_host: ec2-54-241-69-184.us-west-1.compute.amazonaws.com
  external_ip: 54.241.69.184
  internal_host: ip-10-170-26-71.us-west-1.compute.internal
  internal_ip: 10.170.26.71
  zone: us-west-1c
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
